[package]
name = "keylogger"
version = "0.1.0"
authors = ["Ak <akshay.deep0@gmail.com>"]

[dependencies]
winapi = { version = "0.3.4", features = ["winbase"] }
libc = "0.2.17"
user32-sys = "0.1.2"
kernel32-sys = "0.2.2"